# name of the software
name: Prebid.js
# current version of the software
version: 1.1.0
# url of the download button
downloadUrl: https://github.com/prebid/Prebid.js
# licence of the software
license: Apache License
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/prebid/Prebid.js

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/prebid/Prebid.js
  - title: Issues
    url: https://github.com/prebid/Prebid.js/issues?state=open

# header
header:
  #color1: "#0084B4"
  #color1: "#55acee"
  color1: "#3b88c3"
  #color1: "#2ABBB0"
  
  #color1: "#080331"
  #color2: "#673051"
  trianglify: false

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: prebid
  repo: Prebid.js

# twitter buttons
twitter:
  enabled: true
  via:
  hash: prebidjs
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# Build settings
markdown: kramdown

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap